png('plot3.png', width=480, height=480)
plot(data$Sub_metering_1, axes=F, xlab=NA, ylab='Energy sub metering', type='l')
lines(data$Sub_metering_2, col=2)
lines(data$Sub_metering_3, col=4)
box('plot')
axis(1, at=plot2_days, labels=c('Thu','Fri','Sat'))
axis(2)
legend('topright', lty=1, col=c(1,2,4), legend=paste0('Sub_metering', 1:3))
dev.off()
